In [2]:
import numpy as np

In [2]:
a1 = np.array([[1,2,3],[1,1,1],[2,1,3]])
a2 = np.array([[2,2,2],[1,3,1],[1,2,3]])

In [3]:
print(f"Dot Product\n{np.dot(a1,a2)}")

Dot Product
[[ 7 14 13]
 [ 4  7  6]
 [ 8 13 14]]


In [6]:
print(f"Transpose of A1\n{np.transpose(a1)}")
print(f"Transpose of A2\n{np.transpose(a2)}")

Transpose of A1
[[1 1 2]
 [2 1 1]
 [3 1 3]]
Transpose of A2
[[2 1 1]
 [2 3 2]
 [2 1 3]]


In [8]:
#Trace -- Sum of diagonal elements
print(f"Trace of A1\n{np.trace(a1)}")
print(f"Trace of A2\n{np.trace(a2)}")

Trace of A1
5
Trace of A2
8


In [9]:
print(f"Rank of A1\n{np.linalg.matrix_rank(a1)}")
print(f"Rank of A2\n{np.linalg.matrix_rank(a2)}")

Rank of A1
3
Rank of A2
3


In [3]:
print(f"Det of A1\n{np.linalg.det(a1)}")
print(f"Det of A2\n{np.linalg.det(a2)}")
print(f"Inverse of A1\n{np.linalg.inv(a1)}")
print(f"Inverse of A2\n{np.linalg.inv(a2)}")
print(f"Eigen Values and Vector of A1\n{np.linalg.eig(a1)}")
print(f"Eigen Values and Vector of A2\n{np.linalg.eig(a2)}")