In [2]:
import numpy as np

In [19]:
#Q1
a=np.array([1,2,3,4,5])
b= np.array([6,7,8,9,5])

print(np.greater(b,a))
print(np.greater_equal(b,a))
print(np.less(a,b))
print(np.less_equal(a,b))
print(np.equal(a,b))

[ True  True  True  True False]
[ True  True  True  True  True]
[ True  True  True  True False]
[ True  True  True  True  True]
[False False False False  True]


In [24]:
#Q2

a= np.arange(30,71,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [26]:
print("identity matrix")
x=np.identity(5,dtype=int)
print(x)

identity matrix
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [28]:
x= np.arange(0,21)
a=np.array(x)
a[9:15]*= -1
print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14  15  16  17
  18  19  20]


In [30]:
a=np.zeros([5,5],dtype=int)
np.fill_diagonal(a,[1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [46]:
a=np.array([[1,2,3,4,5],[10,20,30,40,50]])
print("the array is\n",a)
print("total sum",np.sum(x))
column_sums = np.sum(x, axis=0)
print("Sum of Columns:", column_sums)
row_sums = np.sum(x, axis=0)
print("Sum of Rows:", row_sums)

the array is
 [[ 1  2  3  4  5]
 [10 20 30 40 50]]
total sum 210
Sum of Columns: 210
Sum of Rows: 210


In [54]:
a= np.array([1,2,3,4,5])
print(a)
np.savetxt(r'C:\Users\Aiswarya\Desktop\DS LAB\ex1\array.txt',a)
b=np.loadtxt(r'C:\Users\Aiswarya\Desktop\DS LAB\ex1\array.txt')
print(b)

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [57]:
a=np.array([2,4,6,8,10])
b=np.array([1,3,5,7,9])
isequal=np.equal(a,b)

if isequal.any():
    print("elements are equal")
else:
    print("elements are not equal")


elements are not equal


In [65]:
a=np.random.randint(30,size=(5,5))
print(a)
print("\n\n")
a[[0,4]]=a[[4,0]]
print(a)

[[ 6  3 14  2 23]
 [25  7 15 29  5]
 [10  5  2 14  6]
 [ 0 10 29 15 27]
 [25  9  8 11 21]]



[[25  9  8 11 21]
 [25  7 15 29  5]
 [10  5  2 14  6]
 [ 0 10 29 15 27]
 [ 6  3 14  2 23]]


In [68]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c=np.multiply(a,b)
print("first array:\n",a)
print("second array: \n",b)
print("product:\n",c)

first array:
 [1 2 3 4 5]
second array: 
 [1 2 3 4 5]
product:
 [ 1  4  9 16 25]


In [3]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
a2 = np.arange(0,31,1)
a2[(a2>=10) & (a2<=20)] *= -1
print(a2)

[  0   1   2   3   4   5   6   7   8   9 -10 -11 -12 -13 -14 -15 -16 -17
 -18 -19 -20  21  22  23  24  25  26  27  28  29  30]


In [ ]:
diagMatrix = np.diag([1,2,3,4,5])
print(diagMatrix)

In [6]:
diagMatrix2 = np.zeros([5,5])
print("Before Filling\n",diagMatrix2)
diagMatrix3 = np.fill_diagonal(diagMatrix2,[9,9,9,9,9])
print("After Filling\n",diagMatrix2)

Before Filling
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
After Filling
 [[9. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0.]
 [0. 0. 9. 0. 0.]
 [0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 9.]]


In [9]:
a4 = np.matrix([[1,2,3],[3,2,1],[3,3,3]])
print(np.linalg.inv(a4))


[[-1.68884986e+15 -1.68884986e+15  2.25179981e+15]
 [ 3.37769972e+15  3.37769972e+15 -4.50359963e+15]
 [-1.68884986e+15 -1.68884986e+15  2.25179981e+15]]


In [11]:
a5 = np.array([[1,2,3],[2,3,4],[3,4,5]])
a6 = np.matrix([[1,2,3],[2,3,4],[3,4,5]])
print(a5)
print(a6)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
[[1 2 3]
 [2 3 4]
 [3 4 5]]


In [13]:
print(np.sum(a5))
print(np.sum(a6))
print(a5+a6)
print(a5-a6)
print(a5*a6)

27
27
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[14 20 26]
 [20 29 38]
 [26 38 50]]


In [16]:
a7 = np.array([[1,2,4],[3,3,4],[6,4,5]])
print(a7)
print(np.sum(a7,axis=0)) #Column Sum when Axis = 0
print(np.sum(a7,axis=1)) #Row Sum when Axis = 1

[[1 2 4]
 [3 3 4]
 [6 4 5]]
[10  9 13]
[ 7 10 15]


In [18]:
np.savetxt("SampleArray1.txt",a7,fmt="%d")
load = np.loadtxt('SampleArray1.txt',dtype=int)
print(load)

[[1 2 4]
 [3 3 4]
 [6 4 5]]


In [21]:
a8 = np.random.randint(0,10,size=(4,4))
print(a8)
a9 = a8
a10 = a8
a9[[0,-1],:] = a8[[-1,0],:]
# a10[:,[0,-1]] = a8[:,[-1,0]]
print(a9)
# print(a10)

[[5 2 1 4]
 [1 9 0 6]
 [2 7 9 8]
 [2 3 4 6]]
[[2 3 4 6]
 [1 9 0 6]
 [2 7 9 8]
 [5 2 1 4]]


In [22]:
print(np.multiply(a9,a8))

[[ 4  9 16 36]
 [ 1 81  0 36]
 [ 4 49 81 64]
 [25  4  1 16]]
